import math
import os
import time
from typing import Optional

import numpy as np
from qblox_instruments import Cluster, ClusterType
from spacq.devices.qblox.qblox_cluster import QbloxCluster, QbloxModule, QbloxChannelResource
import spacq.Libraries.QbloxSequenceHelpers.sequence_helperV3 as sh


class QbloxVideoBackend:
    """
    Videomode backend for qblox, assumes that output and input are both generated by the qblox cluster. 
    For multi device backends, create or use another class. 
    """
    def __init__(self, device: QbloxCluster):
        """
        Initialize the QbloxVideoBackend. 
        """
        self.device = device

    def prepare_and_run(self, config: dict) -> dict:
        """
        Prepare and start a video-mode sweep in the mode given by config["mode"].

        "direct" (default) acquires whatever signal arrives at acq_channel.
        "set_readout" also plays a probe tone from the QRM and demodulates what comes back.
        """
        mode = config.get("mode", "direct")
        if mode == "direct":
            return self.prepare_and_run_direct(config)
        if mode == "set_readout":
            return self.prepare_and_run_set_readout(config)
        raise ValueError(f"Unknown mode {mode!r}; expected 'direct' or 'set_readout'.")

    def prepare_and_run_direct(self, config: dict) -> dict:
        """Sweep X and Y and acquire the signal at acq_channel as it arrives."""
        return self._prepare_and_run(config)

    def prepare_and_run_set_readout(self, config: dict) -> dict:
        """
        Sweep X and Y while the acquisition QRM plays a probe tone and demodulates the return.

        Besides the usual channels this needs:
        - readout_channel: the acquisition module's output that carries the tone.
        - readout_options: {"frequency_Hz": tone/demodulation frequency, "amplitude_mV": tone peak amplitude}.
        """
        readout_channel = config.get("readout_channel")
        readout_options = config.get("readout_options")
        if readout_channel is None or not readout_options:
            raise ValueError("set_readout mode needs readout_channel and readout_options.")

        try:
            frequency_Hz = float(readout_options["frequency_Hz"])
            amplitude_mV = float(readout_options["amplitude_mV"])
        except (KeyError, TypeError, ValueError) as error:
            raise ValueError(
                "readout_options needs numeric frequency_Hz and amplitude_mV."
            ) from error
        if not abs(frequency_Hz) <= 500e6:
            raise ValueError("readout frequency_Hz must be within +/-500 MHz.")

        return self._prepare_and_run(config, readout_channel, frequency_Hz, amplitude_mV)

    def _prepare_and_run(
        self,
        config: dict,
        readout_channel=None,
        readout_frequency_Hz=None,
        readout_amplitude_mV=None,
    ) -> dict:
        """
        This method prepares the qblox modules and sequencers for a video-mode acquisition of a continuous 2D sweep. 
        The method is build around the assumption that each axis is controlled by one output, i.e. non-virtualized gates.
        The configuration dictionary should include the following keys:
        - x_channel: QbloxChannelResource for the X axis control.
        - y_channel: QbloxChannelResource for the Y axis control.
        - acq_channel: QbloxChannelResource for the acquisition channel.

        optional:
            - sequence_options: Optional dictionary with sequence creation options.
            - waveform_options: Optional dictionary with waveform creation options.
        
        Parameters:
            config (dict): Configuration dictionary containing channel resources and sequence options.

        Returns:
            dict: Dictionary containing prepared modules, sequencers, and the uploaded sequence.
        """
        self.config = config

        # Channels are resources resolved from user-configured labels
        x_channel = config.get("x_channel")
        y_channel = config.get("y_channel")
        acq_channel = config.get("acq_channel")
        if any(channel is None for channel in (x_channel, y_channel, acq_channel)):
            raise ValueError(
                "Provide x_channel, y_channel, and acq_channel resources "
                "resolved from the configured resource labels."
            )

        # this will yield the qblox module class (QbloxClusterModule) we actually want to have direct control over the modules
        x_module = x_channel.module     
        y_module = y_channel.module
        acq_module = acq_channel.module
        
        modules = {id(module): module for module in (x_module, y_module, acq_module)}

        if not acq_module.is_qrm_type:
            raise ValueError("QRM module expected for acquisition.")

        readout_amplitude = None
        if readout_channel is not None:
            if readout_channel.module is not acq_module or readout_channel.output_index is None:
                raise ValueError("readout_channel must be an output of the acquisition module.")
            readout_amplitude = readout_amplitude_mV / self._max_voltage_mV(acq_module)
            if not 0 < readout_amplitude <= 1:
                raise ValueError("readout amplitude_mV must be above 0 and within the module's output range.")

        # The sweep and acquisition programs differ but must have identical per-pixel timing.
        sequence_options = config.get("sequence_options", {})
        sequences = self._create_sequences(x_module, y_module, **sequence_options)

        sequencers = {
            'x': x_module.sequencer0,
            'y': y_module.sequencer0,
            'acq': acq_module.sequencer1,
        }

        # x and y may share a sequencer, which must only be armed and started once.
        seq_targets = list(dict.fromkeys([(x_module, 0), (y_module, 0), (acq_module, 1)]))

        # Other signals may be running on these modules, so only touch our own sequencers.
        for module, seq_ind in seq_targets:
            self._release_sequencer(module, seq_ind)
            
        # connect channels to the sequencers of the corrsponding modules
        # the program drives path0 (I) with the X code and path1 (Q) with the Y code
        x_channel.connect_output(sequencers['x'], path="I") 
        y_channel.connect_output(sequencers['y'], path="Q") 
        acq_channel.connect_input(sequencers['acq'], path="I")

        if readout_channel is not None:
            readout_channel.connect_output(sequencers['acq'], path="I")
            sequencers['acq'].mod_en_awg(True)
            sequencers['acq'].nco_freq(readout_frequency_Hz)
            sequencers['acq'].demod_en_acq(True)
            # A static DC offset modulated by the NCO is the probe tone.
            sequencers['acq'].offset_awg_path0(readout_amplitude) 

        # enable sync for the sequencers
        sequencers['x'].sync_en(True)
        sequencers['y'].sync_en(True)
        sequencers['acq'].sync_en(True)

        # The acquire instruction's time is only a wait; this sets the real integration window.
        sequencers['acq'].integration_length_acq(sequence_options.get("integration_time_ns", 1000))

        # upload the sequence 
        for sequencer in {sequencers['x'], sequencers['y']}:
            sequencer.sequence(sequences["sweep"])
        sequencers['acq'].sequence(sequences["acquire"])

        for module, seq_ind in seq_targets:
            module.arm_sequencer(seq_ind)

        # Start only our sequencers; wait_sync lines them up.
        for module, seq_ind in seq_targets:
            module.start_sequencer(seq_ind)
        
        return {
            "modules": modules,
            "sequencers": sequencers,
            "mode": "direct" if readout_channel is None else "set_readout",
            "sequences": sequences,
            "seq_targets": seq_targets,
            "sequencers": sequencers,
        }
    
    @staticmethod
    def _release_sequencer(module, seq_ind):
        """Stop one sequencer and turn off its I/O connections and modulation."""
        module.stop_sequencer(seq_ind)
        sequencer = module.sequencers[seq_ind]
        for name, parameter in sequencer.parameters.items():
            if name.startswith(("connect_out", "connect_acq")):
                parameter("off")
            elif name in ("mod_en_awg", "demod_en_acq"):
                parameter(False)
            elif name in ("offset_awg_path0", "offset_awg_path1"):
                parameter(0)

    def stop(self, seq_targets):
        for module, seq_ind in seq_targets:
            module.stop_sequencer(seq_ind)
            # Keeps a probe tone from outliving the sweep.
            sequencer = module.sequencers[seq_ind]
            sequencer.offset_awg_path0(0)
            sequencer.offset_awg_path1(0)

        return [module.get_sequencer_status(seq_ind) for module, seq_ind in seq_targets]

    def _create_sequences(
        self,
        x_module,
        y_module,
        x_window_mV: tuple[float, float] = (-50.0, 50.0),
        y_window_mV: tuple[float, float] = (-50.0, 50.0),
        x_num_steps: int = 8,
        y_num_steps: int = 8,
        integration_time_ns: int = 1000,
        settle_time_ns: int = 1000,
        interleave: bool = False,
    ) -> dict:
        """Create the Q1ASM sweep for the X/Y outputs and the acquisition program for the QRM."""
        # detemine whether the requested voltage windows are within the mo
        x_max_voltage_mV = self._max_voltage_mV(x_module)
        y_max_voltage_mV = self._max_voltage_mV(y_module)
        
        if len(x_window_mV) != 2 or len(y_window_mV) != 2:
            raise ValueError("Each voltage window must contain (start_mV, end_mV).")
        if not all(math.isfinite(value) for value in (*x_window_mV, *y_window_mV)):
            raise ValueError("Sweep endpoints must be finite voltages in mV.")
        if any(abs(value) > x_max_voltage_mV for value in x_window_mV):
            raise ValueError(
                f"X sweep endpoints must be within +/-{x_max_voltage_mV} mV."
            )
        if any(abs(value) > y_max_voltage_mV for value in y_window_mV):
            raise ValueError(
                f"Y sweep endpoints must be within +/-{y_max_voltage_mV} mV."
            )
        if not isinstance(x_num_steps, int) or x_num_steps < 2:
            raise ValueError("x_num_steps must be an integer of at least 2.")
        if not isinstance(y_num_steps, int) or y_num_steps < 2:
            raise ValueError("y_num_steps must be an integer of at least 2.")
        if (
            not isinstance(integration_time_ns, int)
            or not 4 <= integration_time_ns <= 16384
            or integration_time_ns % 4
        ):
            raise ValueError(
                "integration_time_ns must be a multiple of 4 from 4 to 16384 ns."
            )
        if not isinstance(settle_time_ns, int) or settle_time_ns < 0:
            raise ValueError("settle_time_ns must be a non-negative integer in ns.")
        if settle_time_ns % 4:
            raise ValueError("settle_time_ns must be a multiple of 4 ns.")

        max_dac_int = 32767
        x_start_mV, x_end_mV = x_window_mV
        y_start_mV, y_end_mV = y_window_mV
        x_start_dac = round(x_start_mV / x_max_voltage_mV * max_dac_int)
        x_end_dac = round(x_end_mV / x_max_voltage_mV * max_dac_int)
        y_start_dac = round(y_start_mV / y_max_voltage_mV * max_dac_int)
        y_end_dac = round(y_end_mV / y_max_voltage_mV * max_dac_int)
        x_step_dac = round((x_end_dac - x_start_dac) / (x_num_steps - 1))
        y_step_dac = round((y_end_dac - y_start_dac) / (y_num_steps - 1))
        x_start_q1 = x_start_dac & 0xFFFFFFFF
        y_start_q1 = y_start_dac & 0xFFFFFFFF

        x_step_instruction = (f"add R1,{x_step_dac},R1" if x_step_dac >= 0
                              else f"sub R1,{-x_step_dac},R1"
                             )
        y_step_instruction = (f"add R2,{y_step_dac},R2" if y_step_dac >= 0
                              else f"sub R2,{-y_step_dac},R2"
                             )

        # Every program spends 4 ns + settle + integration per pixel so wait_sync keeps them aligned.
        def wait_lines(duration_ns, comment):
            # A single wait is limited, so long durations are split into chunks.
            lines = []
            while duration_ns > 0:
                chunk_ns = min(duration_ns, 65532)
                lines.append(f"wait {chunk_ns}    # {comment}")
                duration_ns -= chunk_ns
            return lines

        sweep_lines = [
            "wait_sync 4                        # synchronize this sequencer",
            "frame_loop:                        # restart the sweep",
            f"move {x_start_q1},R1              # initialize the X output DAC code",
            f"move {x_num_steps},R3             # number of X rows to scan",
            "x_loop:                            # start one row of the 2D scan",
            f"move {y_start_q1},R2              # reset Y to its start for each X row",
            f"move {y_num_steps},R4             # number of pixels in this Y row",
            "y_loop:                            # start one pixel",
            "set_awg_offs R1,R2                 # apply the current X and Y DAC codes",
            "upd_param 4                        # wait 4 ns for the output update to take effect",
            *wait_lines(settle_time_ns + integration_time_ns, "hold while the pixel settles and is measured"),
            f"{y_step_instruction}                  # advance the Y DAC code",
            "loop R4,@y_loop                        # repeat until this row has all Y points",
            f"{x_step_instruction}                  # advance the X DAC code for the next row",
            "loop R3,@x_loop                        # repeat until all X rows are scanned",
            "jmp @frame_loop                        # video mode: sweep forever",
        ]

        acquire_lines = [
            "wait_sync 4                        # synchronize this sequencer",
            "frame_loop:                        # restart the sweep, overwriting this frame's bins",
            "move 0,R0                          # acquisition-bin index for the first pixel",
            f"move {x_num_steps},R3             # number of X rows to scan",
            "x_loop:                            # start one row of the 2D scan",
            f"move {y_num_steps},R4             # number of pixels in this Y row",
            "y_loop:                            # start one pixel",
            *wait_lines(4 + settle_time_ns, "match the sweep's output update and settling"),
            f"acquire 0,R0,{integration_time_ns}    # integrate this pixel, overwriting the previous frame's bin",
            "add R0,1,R0                            # advance to the next pixel's acquisition bin",
            "loop R4,@y_loop                        # repeat until this row has all Y points",
            "loop R3,@x_loop                        # repeat until all X rows are scanned",
            "jmp @frame_loop                        # video mode: sweep forever, re-using the same bins",
        ]

        return {
            "sweep": {
                "waveforms": {},
                "weights": {},
                "acquisitions": {},
                "program": "\n".join(sweep_lines),
            },
            "acquire": {
                "waveforms": {},
                "weights": {},
                "acquisitions": {
                    "frame": {
                        "num_bins": x_num_steps * y_num_steps,
                        "index": 0,
                    }
                },
                "program": "\n".join(acquire_lines),
            },
        }

    def _create_waveform_sequence(self,
                                  x_num_steps: int,
                                  y_num_steps: int,
                                  ) -> dict:
        # Placeholder implementation for creating a waveform sequence
        program_lines = []
        return {
            "waveforms": {},
            "weights": {},
            "acquisitions": {
                "frame": {
                    "num_bins": x_num_steps * y_num_steps,
                    "index": 0,
                }
            },
            "program": "\n".join(program_lines),
        }

    @staticmethod
    def _max_voltage_mV(module) -> int:
        if module.is_qcm_type:
            return 2500
        if module.is_qrm_type:
            return 500
        raise ValueError("Only baseband QCM and QRM modules are supported.")

    def _construct_frame(
        self,
        voltage_window: dict,
        acquisition_data: dict,
        acquisition_name: str = "frame",
        channel: str = "path0",
    ) -> dict:
        """
        Description:
        Reshape one Qblox acquisition's integration bins into a video frame.

        Parameters:
        ----------
        voltage_window : dict
            The sweep configuration containing x_window_mV, y_window_mV, x_num_steps, and y_num_steps.
        acquisition_data : dict
            The raw acquisition data from the Qblox module.
        acquisition_name : str, optional
            The name of the acquisition to process (default is "frame").
        channel : str, optional
            The channel to extract ("path0", "path1", or "magnitude"; default is "path0").
        """
        try:
            x_window_mV = voltage_window["x_window_mV"]
            y_window_mV = voltage_window["y_window_mV"]
            x_num_steps = voltage_window["x_num_steps"]
            y_num_steps = voltage_window["y_num_steps"]
        except (KeyError, TypeError) as error:
            raise ValueError(
                "voltage_window must include both axis windows and step counts."
            ) from error

        if channel not in ("path0", "path1", "magnitude"):
            raise ValueError("channel must be 'path0', 'path1', or 'magnitude'.")

        try:
            acquisition = acquisition_data[acquisition_name]["acquisition"]
            integration_bins = acquisition["bins"]["integration"]
        except (KeyError, TypeError) as error:
            raise ValueError(
                f"Acquisition data does not contain integration bins for {acquisition_name!r}."
            ) from error

        expected_bins = x_num_steps * y_num_steps
        try:
            path0 = np.asarray(integration_bins["path0"], dtype=float).reshape(-1)
            if channel == "magnitude":
                path1 = np.asarray(integration_bins["path1"], dtype=float).reshape(-1)
        except (KeyError, TypeError, ValueError) as error:
            raise ValueError(f"Missing or invalid acquisition data for {channel}.") from error

        if path0.size != expected_bins:
            raise ValueError(
                f"Expected {expected_bins} bins for a {x_num_steps}x{y_num_steps} frame, "
                f"received {path0.size}."
            )
        if channel == "path0":
            values = path0
        elif channel == "path1":
            try:
                values = np.asarray(integration_bins["path1"], dtype=float).reshape(-1)
            except (KeyError, TypeError, ValueError) as error:
                raise ValueError("Missing or invalid acquisition data for path1.") from error
            if values.size != expected_bins:
                raise ValueError(
                    f"Expected {expected_bins} path1 bins, received {values.size}."
                )
        else:
            if path1.size != expected_bins:
                raise ValueError(
                    f"Expected {expected_bins} path1 bins, received {path1.size}."
                )
            values = np.hypot(path0, path1)

        x_axis_mV = np.linspace(x_window_mV[0], x_window_mV[1], x_num_steps)
        y_axis_mV = np.linspace(y_window_mV[0], y_window_mV[1], y_num_steps)
        return {
            "values": values.reshape(x_num_steps, y_num_steps),
            "x_mV": x_axis_mV,
            "y_mV": y_axis_mV,
            "channel": channel,
        }

    def stream_frames(
        self,
        run_result: dict,
        voltage_window: dict,
        acquisition_name: str = "frame",
        channel: str = "path0",
        poll_interval_s: Optional[float] = None,
    ):
        """
        Continuously poll and yield frames while the Q1ASM program loops forever.

        Parameters:
        ----------
        run_result : dict
            The result dictionary returned by ``prepare_and_run`` containing sequencer information.
        voltage_window : dict
            The sweep configuration containing x_window_mV, y_window_mV, x_num_steps, and y_num_steps.
        acquisition_name : str, optional
            The name of the acquisition to process (default is "frame").
        channel : str, optional
            The channel to extract ("path0", "path1", or "magnitude"; default is "path0").
        poll_interval_s : float, optional
            The interval in seconds between polling the sequencer for new frames. If None, it is calculated based on the frame time.

        Yields:
        ------
        dict
            A dictionary containing the reshaped frame values, x and y axes in mV, and the channel name.

        """
        acq_sequencer = run_result["sequencers"]["acq"]

        if poll_interval_s is None:
            integration_time_ns = voltage_window.get("integration_time_ns", 1000)
            settle_time_ns = voltage_window.get("settle_time_ns", 1000)
            num_bins = voltage_window["x_num_steps"] * voltage_window["y_num_steps"]
            frame_time_s = num_bins * (integration_time_ns + settle_time_ns) * 1e-9
            poll_interval_s = frame_time_s / 4

        while True:
            # TODO: verify get_acquisitions()/bin-overwrite behaviour against the real sequencer API.
            acquisition_data = acq_sequencer.get_acquisitions()
            yield self._construct_frame(voltage_window, acquisition_data, acquisition_name, channel)
            time.sleep(poll_interval_s)

#%% --- TESTS --- ###
DUMMY_CLUSTER_CONFIG = {
    2: ClusterType.CLUSTER_QCM,
    4: ClusterType.CLUSTER_QRM,
    6: ClusterType.CLUSTER_QCM_RF,
}

HARDWARE_TEST_CONFIG = {
    "cluster_ip": "169.254.12.10",
    "module_slot": 4,
    "sequencer_index": 0,
    "x_window_mV": (-50.0, 50.0),
    "y_window_mV": (-50.0, 50.0),
    "x_num_steps": 8,
    "y_num_steps": 8,
    "integration_time_ns": 1000,
    "settle_time_ns": 1000,
}

USE_HARDWARE_FOR_DEMO = False

def _print_test_program(cluster: Cluster, config: dict) -> dict:
    module = next(
        module
        for module in cluster.modules
        if module.slot_idx == config["module_slot"]
    )
    sequences = QbloxVideoBackend(cluster)._create_sequences(
        module,
        module,
        x_window_mV=config["x_window_mV"],
        y_window_mV=config["y_window_mV"],
        x_num_steps=config["x_num_steps"],
        y_num_steps=config["y_num_steps"],
        integration_time_ns=config["integration_time_ns"],
        settle_time_ns=config["settle_time_ns"],
    )
    sequencer = getattr(module, f"sequencer{config['sequencer_index']}")
    for name, sequence in sequences.items():
        sequencer.sequence(sequence)
        print(f"--- {name} program ---\n{sequence['program']}")
    return sequences

if __name__ == "__main__":
    if USE_HARDWARE_FOR_DEMO:
        device = Cluster(
            "qblox_video_hardware_test",
            identifier=HARDWARE_TEST_CONFIG["cluster_ip"],
        )
        print("Uploading only; the sequencer is not armed or started.")
    else:
        device = Cluster(
            "qblox_video_dummy_test",
            dummy_cfg=DUMMY_CLUSTER_CONFIG,
        )

    try:
        _print_test_program(device, HARDWARE_TEST_CONFIG)
    finally:
        device.close()