import math
import os
import time
from typing import Optional

import numpy as np
from qblox_instruments import Cluster, ClusterType
from spacq.devices.qblox.qblox_cluster import QbloxCluster, QbloxModule, QbloxChannelResource
import spacq.Libraries.QbloxSequenceHelpers.sequence_helperV3 as sh


class QbloxVideoBackend:
    """
    Videomode backend for qblox, assumes that output and input are both generated by the qblox cluster. 
    For multi device backends, create or use another class. 
    """
    def __init__(self, device: QbloxCluster):
        """
        Initialize the QbloxVideoBackend. 
        """
        self.device = device

    def prepare_and_run_qblox(self, config: dict) -> dict:
        """
        This method prepares the qblox modules and sequencers for a video-mode acquisition of a continuous 2D sweep. 
        The method is build around the assumption that each axis is controlled by one output, i.e. non-virtualized gates.
        The configuration dictionary should include the following keys:
        - x_channel: QbloxChannelResource for the X axis control.
        - y_channel: QbloxChannelResource for the Y axis control.
        - acq_channel: QbloxChannelResource for the acquisition channel.

        optional:
            - sequence_options: Optional dictionary with sequence creation options.
            - waveform_options: Optional dictionary with waveform creation options.
        
        Parameters:
            config (dict): Configuration dictionary containing channel resources and sequence options.

        Returns:
            dict: Dictionary containing prepared modules, sequencers, and the uploaded sequence.
        """
        cluster = self.device.cluster
        cluster.reset()
        time.sleep(0.1)  # Give the cluster some time to reset

        self.config = config

        # Channels are resources resolved from user-configured labels
        x_channel = config.get("x_channel")
        y_channel = config.get("y_channel")
        acq_channel = config.get("acq_channel")
        if any(channel is None for channel in (x_channel, y_channel, acq_channel)):
            raise ValueError(
                "Provide x_channel, y_channel, and acq_channel resources "
                "resolved from the configured resource labels."
            )

        # this will yield the qblox module class (QbloxClusterModule) we actually want to have direct control over the modules
        x_module = x_channel.module     
        y_module = y_channel.module
        acq_module = acq_channel.module
        
        modules = {id(module): module for module in (x_module, y_module, acq_module)}

        if not acq_module.is_qrm_type:
            raise ValueError("QRM module expected for acquisition.")

        # Every sequencer runs the same wait_sync'd program, so build it once.
        sequence_options = config.get("sequence_options", {})
        sequence = self._create_sequence(x_module, y_module, **sequence_options)

        sequencers = {
            'x': x_module.sequencer0,
            'y': y_module.sequencer0,
            'acq': acq_module.sequencer1,
        }

        seq_targets = [(x_module.slot_idx, 0), (y_module.slot_idx, 0), (acq_module.slot_idx, 1)]

        # disconnect existing I/O and configure the sequencer connections.
        for module in modules.values():
            sh.disconnect_io(module)
            
        # measure and apply I/Q offsets before the frame ac quisition.
        sh.acquire_scope_and_calc_offsets(acq_module)
        sh.disconnect_io(acq_module)

        # connect channels to the sequencers of the corrsponding modules
        # connect x and y to separate paths to match sequence conventions
        x_channel.connect_output(sequencers['x'], path="I") 
        y_channel.connect_output(sequencers['y'], path="O") 
        acq_channel.connect_input(sequencers['acq'], path="I") 

        # enable sync for the sequencers
        sequencers['x'].enable_sync(True)
        sequencers['y'].enable_sync(True)
        sequencers['acq'].enable_sync(True)

        # upload the sequence 
        # using a set to avoid uploading the same sequence to the same sequencer multiple times
        for sequencer in set(sequencers.values()):
            sequencer.sequence(sequence)

        # arm and start the sequencers
        cluster.arm_sequencers(seq_targets = seq_targets)
        cluster.start_sequencers(seq_targets = seq_targets)
        
        return {
            "modules": modules,
            "sequence": sequence,
            "seq_targets": seq_targets,
        }
    
    def stop(self, cluster, seq_targets):
        cluster.stop_sequencers(seq_targets=seq_targets)
        cluster.get_sequencer_status(seq_targets=seq_targets)

    def _create_sequence(
        self,
        x_module,
        y_module,
        x_window_mV: tuple[float, float] = (-50.0, 50.0),
        y_window_mV: tuple[float, float] = (-50.0, 50.0),
        x_num_steps: int = 8,
        y_num_steps: int = 8,
        integration_time_ns: int = 1000,
        settle_time_ns: int = 1000,
        interleave: bool = False,
    ) -> dict:
        """Create a compact nested-loop Q1ASM sweep and its acquisition bins."""
        # detemine whether the requested voltage windows are within the mo
        x_max_voltage_mV = self._max_voltage_mV(x_module)
        y_max_voltage_mV = self._max_voltage_mV(y_module)
        
        if len(x_window_mV) != 2 or len(y_window_mV) != 2:
            raise ValueError("Each voltage window must contain (start_mV, end_mV).")
        if not all(math.isfinite(value) for value in (*x_window_mV, *y_window_mV)):
            raise ValueError("Sweep endpoints must be finite voltages in mV.")
        if any(abs(value) > x_max_voltage_mV for value in x_window_mV):
            raise ValueError(
                f"X sweep endpoints must be within +/-{x_max_voltage_mV} mV."
            )
        if any(abs(value) > y_max_voltage_mV for value in y_window_mV):
            raise ValueError(
                f"Y sweep endpoints must be within +/-{y_max_voltage_mV} mV."
            )
        if not isinstance(x_num_steps, int) or x_num_steps < 2:
            raise ValueError("x_num_steps must be an integer of at least 2.")
        if not isinstance(y_num_steps, int) or y_num_steps < 2:
            raise ValueError("y_num_steps must be an integer of at least 2.")
        if (
            not isinstance(integration_time_ns, int)
            or not 4 <= integration_time_ns <= 16384
            or integration_time_ns % 4
        ):
            raise ValueError(
                "integration_time_ns must be a multiple of 4 from 4 to 16384 ns."
            )
        if not isinstance(settle_time_ns, int) or settle_time_ns < 0:
            raise ValueError("settle_time_ns must be a non-negative integer in ns.")
        if settle_time_ns % 4:
            raise ValueError("settle_time_ns must be a multiple of 4 ns.")

        max_dac_int = 32767
        x_start_mV, x_end_mV = x_window_mV
        y_start_mV, y_end_mV = y_window_mV
        x_start_dac = round(x_start_mV / x_max_voltage_mV * max_dac_int)
        x_end_dac = round(x_end_mV / x_max_voltage_mV * max_dac_int)
        y_start_dac = round(y_start_mV / y_max_voltage_mV * max_dac_int)
        y_end_dac = round(y_end_mV / y_max_voltage_mV * max_dac_int)
        x_step_dac = round((x_end_dac - x_start_dac) / (x_num_steps - 1))
        y_step_dac = round((y_end_dac - y_start_dac) / (y_num_steps - 1))
        x_start_q1 = x_start_dac & 0xFFFFFFFF
        y_start_q1 = y_start_dac & 0xFFFFFFFF

        x_step_instruction = (f"add R1,{x_step_dac},R1" if x_step_dac >= 0
                              else f"sub R1,{x_step_dac},R1"
                             )
        y_step_instruction = (f"add R2,{y_step_dac},R2" if y_step_dac >= 0
                              else f"sub R2,{y_step_dac},R2"
                             )

        # Initialize the program with synchronization and loop setup.
        program_lines = [
            "wait_sync 4                        # synchronize this sequencer",
            "frame_loop:                        # restart the sweep, overwriting this frame's bins",
            "move 0,R0                          # acquisition-bin index for the first pixel",
            f"move {x_start_q1},R1              # initialize the X output DAC code",
            f"move {x_num_steps},R3             # number of X rows to scan",
            "x_loop:                            # start one row of the 2D scan",
            f"move {y_start_q1},R2              # reset Y to its start for each X row",
            f"move {y_num_steps},R4             # number of pixels in this Y row",
            "y_loop:                            # start one pixel measurement",
            "set_awg_offs R1,R2                 # apply the current X and Y DAC codes",
            "upd_param 4                        # wait 4 ns for the output update to take effect",
        ]

        # Split the settling time into chunks of at most 65532 ns to fit the sequencer's wait instruction.
        remaining_settle_ns = settle_time_ns
        while remaining_settle_ns > 0:
            wait_chunk_ns = min(remaining_settle_ns, 65532)
            program_lines.append(
                f"wait {wait_chunk_ns} # allow this chunk of the settling time"
            )
            remaining_settle_ns -= wait_chunk_ns

        # Add the acquisition and loop instructions for the 2D scan.
        program_lines.extend((
            f"acquire 0,R0,{integration_time_ns}    # integrate this pixel, overwriting the previous frame's bin",
            "add R0,1,R0                            # advance to the next pixel's acquisition bin",
            f"{y_step_instruction}                  # advance the Y DAC code",
            "loop R4,@y_loop                        # repeat until this row has all Y points",
            f"{x_step_instruction}                  # advance the X DAC code for the next row",
            "loop R3,@x_loop                        # repeat until all X rows are scanned",
            "jmp @frame_loop                        # video mode: sweep forever, re-using the same bins",
        ))

        return {
            "waveforms": {},
            "weights": {},
            "acquisitions": {
                "frame": {
                    "num_bins": x_num_steps * y_num_steps,
                    "index": 0,
                }
            },
            "program": "\n".join(program_lines),
        }

    def _create_waveform_sequence(self,
                                  x_num_steps: int,
                                  y_num_steps: int,
                                  ) -> dict:
        # Placeholder implementation for creating a waveform sequence
        program_lines = []
        return {
            "waveforms": {},
            "weights": {},
            "acquisitions": {
                "frame": {
                    "num_bins": x_num_steps * y_num_steps,
                    "index": 0,
                }
            },
            "program": "\n".join(program_lines),
        }
    
    @staticmethod
    def _max_voltage_mV(module) -> int:
        if module.is_qcm_type:
            return 2500
        if module.is_qrm_type:
            return 500
        raise ValueError("Only baseband QCM and QRM modules are supported.")

    def _construct_frame(
        self,
        voltage_window: dict,
        acquisition_data: dict,
        acquisition_name: str = "frame",
        channel: str = "path0",
    ) -> dict:
        """
        Description:
        Reshape one Qblox acquisition's integration bins into a video frame.

        Parameters:
        ----------
        voltage_window : dict
            The sweep configuration containing x_window_mV, y_window_mV, x_num_steps, and y_num_steps.
        acquisition_data : dict
            The raw acquisition data from the Qblox module.
        acquisition_name : str, optional
            The name of the acquisition to process (default is "frame").
        channel : str, optional
            The channel to extract ("path0", "path1", or "magnitude"; default is "path0").
        """
        try:
            x_window_mV = voltage_window["x_window_mV"]
            y_window_mV = voltage_window["y_window_mV"]
            x_num_steps = voltage_window["x_num_steps"]
            y_num_steps = voltage_window["y_num_steps"]
        except (KeyError, TypeError) as error:
            raise ValueError(
                "voltage_window must include both axis windows and step counts."
            ) from error

        if channel not in ("path0", "path1", "magnitude"):
            raise ValueError("channel must be 'path0', 'path1', or 'magnitude'.")

        try:
            acquisition = acquisition_data[acquisition_name]["acquisition"]
            integration_bins = acquisition["bins"]["integration"]
        except (KeyError, TypeError) as error:
            raise ValueError(
                f"Acquisition data does not contain integration bins for {acquisition_name!r}."
            ) from error

        expected_bins = x_num_steps * y_num_steps
        try:
            path0 = np.asarray(integration_bins["path0"], dtype=float).reshape(-1)
            if channel == "magnitude":
                path1 = np.asarray(integration_bins["path1"], dtype=float).reshape(-1)
        except (KeyError, TypeError, ValueError) as error:
            raise ValueError(f"Missing or invalid acquisition data for {channel}.") from error

        if path0.size != expected_bins:
            raise ValueError(
                f"Expected {expected_bins} bins for a {x_num_steps}x{y_num_steps} frame, "
                f"received {path0.size}."
            )
        if channel == "path0":
            values = path0
        elif channel == "path1":
            try:
                values = np.asarray(integration_bins["path1"], dtype=float).reshape(-1)
            except (KeyError, TypeError, ValueError) as error:
                raise ValueError("Missing or invalid acquisition data for path1.") from error
            if values.size != expected_bins:
                raise ValueError(
                    f"Expected {expected_bins} path1 bins, received {values.size}."
                )
        else:
            if path1.size != expected_bins:
                raise ValueError(
                    f"Expected {expected_bins} path1 bins, received {path1.size}."
                )
            values = np.hypot(path0, path1)

        x_axis_mV = np.linspace(x_window_mV[0], x_window_mV[1], x_num_steps)
        y_axis_mV = np.linspace(y_window_mV[0], y_window_mV[1], y_num_steps)
        return {
            "values": values.reshape(x_num_steps, y_num_steps),
            "x_mV": x_axis_mV,
            "y_mV": y_axis_mV,
            "channel": channel,
        }

    def stream_frames(
        self,
        run_result: dict,
        voltage_window: dict,
        acquisition_name: str = "frame",
        channel: str = "path0",
        poll_interval_s: Optional[float] = None,
    ):
        """
        Continuously poll and yield frames while the Q1ASM program loops forever.

        Parameters:
        ----------
        run_result : dict
            The result dictionary returned by ``prepare_and_run`` containing sequencer information.
        voltage_window : dict
            The sweep configuration containing x_window_mV, y_window_mV, x_num_steps, and y_num_steps.
        acquisition_name : str, optional
            The name of the acquisition to process (default is "frame").
        channel : str, optional
            The channel to extract ("path0", "path1", or "magnitude"; default is "path0").
        poll_interval_s : float, optional
            The interval in seconds between polling the sequencer for new frames. If None, it is calculated based on the frame time.

        Yields:
        ------
        dict
            A dictionary containing the reshaped frame values, x and y axes in mV, and the channel name.

        """
        acq_sequencer = run_result["sequencers"]["acq"]

        if poll_interval_s is None:
            integration_time_ns = voltage_window.get("integration_time_ns", 1000)
            settle_time_ns = voltage_window.get("settle_time_ns", 1000)
            num_bins = voltage_window["x_num_steps"] * voltage_window["y_num_steps"]
            frame_time_s = num_bins * (integration_time_ns + settle_time_ns) * 1e-9
            poll_interval_s = frame_time_s / 4

        while True:
            # TODO: verify get_acquisitions()/bin-overwrite behaviour against the real sequencer API.
            acquisition_data = acq_sequencer.get_acquisitions()
            yield self._construct_frame(voltage_window, acquisition_data, acquisition_name, channel)
            time.sleep(poll_interval_s)

#%% --- TESTS --- ###
DUMMY_CLUSTER_CONFIG = {
    2: ClusterType.CLUSTER_QCM,
    4: ClusterType.CLUSTER_QRM,
    6: ClusterType.CLUSTER_QCM_RF,
}

HARDWARE_TEST_CONFIG = {
    "cluster_ip": "169.254.12.10",
    "module_slot": 4,
    "sequencer_index": 0,
    "x_window_mV": (-50.0, 50.0),
    "y_window_mV": (-50.0, 50.0),
    "x_num_steps": 8,
    "y_num_steps": 8,
    "integration_time_ns": 1000,
    "settle_time_ns": 1000,
}

USE_HARDWARE_FOR_DEMO = False

def _print_test_program(cluster: Cluster, config: dict) -> dict:
    module = next(
        module
        for module in cluster.modules
        if module.slot_idx == config["module_slot"]
    )
    sequence = QbloxVideoBackend(cluster)._create_sequence(
        module,
        module,
        x_window_mV=config["x_window_mV"],
        y_window_mV=config["y_window_mV"],
        x_num_steps=config["x_num_steps"],
        y_num_steps=config["y_num_steps"],
        integration_time_ns=config["integration_time_ns"],
        settle_time_ns=config["settle_time_ns"],
    )
    sequencer = getattr(module, f"sequencer{config['sequencer_index']}")
    sequencer.sequence(sequence)
    print(sequence["program"])
    return sequence

if __name__ == "__main__":
    if USE_HARDWARE_FOR_DEMO:
        device = Cluster(
            "qblox_video_hardware_test",
            identifier=HARDWARE_TEST_CONFIG["cluster_ip"],
        )
        print("Uploading only; the sequencer is not armed or started.")
    else:
        device = Cluster(
            "qblox_video_dummy_test",
            dummy_cfg=DUMMY_CLUSTER_CONFIG,
        )

    try:
        _print_test_program(device, HARDWARE_TEST_CONFIG)
    finally:
        device.close()